package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * AddressStateType generated by hbm2java
 */
public class AddressStateType implements java.io.Serializable {

	private short addressStateTypeId;
	private String code;
	private String name;
	private Set addresses = new HashSet(0);

	public AddressStateType() {
	}

	public AddressStateType(short addressStateTypeId, String code, String name) {
		this.addressStateTypeId = addressStateTypeId;
		this.code = code;
		this.name = name;
	}

	public AddressStateType(short addressStateTypeId, String code, String name,
			Set addresses) {
		this.addressStateTypeId = addressStateTypeId;
		this.code = code;
		this.name = name;
		this.addresses = addresses;
	}

	public short getAddressStateTypeId() {
		return this.addressStateTypeId;
	}

	public void setAddressStateTypeId(short addressStateTypeId) {
		this.addressStateTypeId = addressStateTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
