package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AddressType generated by hbm2java
 */
public class AddressType implements java.io.Serializable {

	private short addressTypeId;
	private Chain chain;
	private Employee employeeByUpdatedBy;
	private Employee employeeByCreatedBy;
	private String code;
	private String name;
	private char leadingSymbol;
	private Date createdAt;
	private Date updatedAt;
	private Set addresses = new HashSet(0);

	public AddressType() {
	}

	public AddressType(short addressTypeId, Chain chain,
			Employee employeeByCreatedBy, String code, String name,
			char leadingSymbol, Date createdAt) {
		this.addressTypeId = addressTypeId;
		this.chain = chain;
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.code = code;
		this.name = name;
		this.leadingSymbol = leadingSymbol;
		this.createdAt = createdAt;
	}

	public AddressType(short addressTypeId, Chain chain,
			Employee employeeByUpdatedBy, Employee employeeByCreatedBy,
			String code, String name, char leadingSymbol, Date createdAt,
			Date updatedAt, Set addresses) {
		this.addressTypeId = addressTypeId;
		this.chain = chain;
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.code = code;
		this.name = name;
		this.leadingSymbol = leadingSymbol;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.addresses = addresses;
	}

	public short getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(short addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public Chain getChain() {
		return this.chain;
	}

	public void setChain(Chain chain) {
		this.chain = chain;
	}

	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
	}

	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getLeadingSymbol() {
		return this.leadingSymbol;
	}

	public void setLeadingSymbol(char leadingSymbol) {
		this.leadingSymbol = leadingSymbol;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
