package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private long addressId;
	private AddressStateType addressStateType;
	private AddressType addressType;
	private Wallet wallet;
	private String label;
	private String encodedForm;
	private BigDecimal balance;
	private Date indexedAt;
	private Date updatedAt;
	private Set paymentRequests = new HashSet(0);
	private Set addressBookEntries = new HashSet(0);
	private Set transactionEndpoints = new HashSet(0);

	public Address() {
	}

	public Address(long addressId, AddressStateType addressStateType,
			AddressType addressType, String encodedForm, Date indexedAt) {
		this.addressId = addressId;
		this.addressStateType = addressStateType;
		this.addressType = addressType;
		this.encodedForm = encodedForm;
		this.indexedAt = indexedAt;
	}

	public Address(long addressId, AddressStateType addressStateType,
			AddressType addressType, Wallet wallet, String label,
			String encodedForm, BigDecimal balance, Date indexedAt,
			Date updatedAt, Set paymentRequests, Set addressBookEntries,
			Set transactionEndpoints) {
		this.addressId = addressId;
		this.addressStateType = addressStateType;
		this.addressType = addressType;
		this.wallet = wallet;
		this.label = label;
		this.encodedForm = encodedForm;
		this.balance = balance;
		this.indexedAt = indexedAt;
		this.updatedAt = updatedAt;
		this.paymentRequests = paymentRequests;
		this.addressBookEntries = addressBookEntries;
		this.transactionEndpoints = transactionEndpoints;
	}

	public long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}

	public AddressStateType getAddressStateType() {
		return this.addressStateType;
	}

	public void setAddressStateType(AddressStateType addressStateType) {
		this.addressStateType = addressStateType;
	}

	public AddressType getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	public Wallet getWallet() {
		return this.wallet;
	}

	public void setWallet(Wallet wallet) {
		this.wallet = wallet;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getEncodedForm() {
		return this.encodedForm;
	}

	public void setEncodedForm(String encodedForm) {
		this.encodedForm = encodedForm;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public Date getIndexedAt() {
		return this.indexedAt;
	}

	public void setIndexedAt(Date indexedAt) {
		this.indexedAt = indexedAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getPaymentRequests() {
		return this.paymentRequests;
	}

	public void setPaymentRequests(Set paymentRequests) {
		this.paymentRequests = paymentRequests;
	}

	public Set getAddressBookEntries() {
		return this.addressBookEntries;
	}

	public void setAddressBookEntries(Set addressBookEntries) {
		this.addressBookEntries = addressBookEntries;
	}

	public Set getTransactionEndpoints() {
		return this.transactionEndpoints;
	}

	public void setTransactionEndpoints(Set transactionEndpoints) {
		this.transactionEndpoints = transactionEndpoints;
	}

}
