package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AddressBookEntry generated by hbm2java
 */
public class AddressBookEntry implements java.io.Serializable {

	private long addressBookEntryId;
	private Address address;
	private Customer customer;
	private String label;
	private Date createdAt;
	private Date updatedAt;

	public AddressBookEntry() {
	}

	public AddressBookEntry(long addressBookEntryId, Address address,
			Customer customer, String label, Date createdAt) {
		this.addressBookEntryId = addressBookEntryId;
		this.address = address;
		this.customer = customer;
		this.label = label;
		this.createdAt = createdAt;
	}

	public AddressBookEntry(long addressBookEntryId, Address address,
			Customer customer, String label, Date createdAt, Date updatedAt) {
		this.addressBookEntryId = addressBookEntryId;
		this.address = address;
		this.customer = customer;
		this.label = label;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public long getAddressBookEntryId() {
		return this.addressBookEntryId;
	}

	public void setAddressBookEntryId(long addressBookEntryId) {
		this.addressBookEntryId = addressBookEntryId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
