package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chain generated by hbm2java
 */
public class Chain implements java.io.Serializable {

	private short chainId;
	private Currency currency;
	private Employee employeeByCreatedBy;
	private Employee employeeByUpdatedBy;
	private String code;
	private String name;
	private Date startedOn;
	private BigDecimal availableSupply;
	private boolean isOperational;
	private Date createdAt;
	private Date updatedAt;
	private Set addressTypes = new HashSet(0);

	public Chain() {
	}

	public Chain(short chainId, Currency currency,
			Employee employeeByCreatedBy, String code, String name,
			Date startedOn, BigDecimal availableSupply, boolean isOperational,
			Date createdAt) {
		this.chainId = chainId;
		this.currency = currency;
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.code = code;
		this.name = name;
		this.startedOn = startedOn;
		this.availableSupply = availableSupply;
		this.isOperational = isOperational;
		this.createdAt = createdAt;
	}

	public Chain(short chainId, Currency currency,
			Employee employeeByCreatedBy, Employee employeeByUpdatedBy,
			String code, String name, Date startedOn,
			BigDecimal availableSupply, boolean isOperational, Date createdAt,
			Date updatedAt, Set addressTypes) {
		this.chainId = chainId;
		this.currency = currency;
		this.employeeByCreatedBy = employeeByCreatedBy;
		this.employeeByUpdatedBy = employeeByUpdatedBy;
		this.code = code;
		this.name = name;
		this.startedOn = startedOn;
		this.availableSupply = availableSupply;
		this.isOperational = isOperational;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.addressTypes = addressTypes;
	}

	public short getChainId() {
		return this.chainId;
	}

	public void setChainId(short chainId) {
		this.chainId = chainId;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public Employee getEmployeeByCreatedBy() {
		return this.employeeByCreatedBy;
	}

	public void setEmployeeByCreatedBy(Employee employeeByCreatedBy) {
		this.employeeByCreatedBy = employeeByCreatedBy;
	}

	public Employee getEmployeeByUpdatedBy() {
		return this.employeeByUpdatedBy;
	}

	public void setEmployeeByUpdatedBy(Employee employeeByUpdatedBy) {
		this.employeeByUpdatedBy = employeeByUpdatedBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartedOn() {
		return this.startedOn;
	}

	public void setStartedOn(Date startedOn) {
		this.startedOn = startedOn;
	}

	public BigDecimal getAvailableSupply() {
		return this.availableSupply;
	}

	public void setAvailableSupply(BigDecimal availableSupply) {
		this.availableSupply = availableSupply;
	}

	public boolean isIsOperational() {
		return this.isOperational;
	}

	public void setIsOperational(boolean isOperational) {
		this.isOperational = isOperational;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getAddressTypes() {
		return this.addressTypes;
	}

	public void setAddressTypes(Set addressTypes) {
		this.addressTypes = addressTypes;
	}

}
