package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private short currencyId;
	private Employee employee;
	private String name;
	private String abbreviation;
	private String symbol;
	private Date launchedOn;
	private int blockTime;
	private BigDecimal standardFee;
	private String websiteUrl;
	private Date createdAt;
	private Date updatedAt;
	private Set chains = new HashSet(0);

	public Currency() {
	}

	public Currency(short currencyId, String name, String abbreviation,
			Date launchedOn, int blockTime, BigDecimal standardFee,
			String websiteUrl, Date createdAt) {
		this.currencyId = currencyId;
		this.name = name;
		this.abbreviation = abbreviation;
		this.launchedOn = launchedOn;
		this.blockTime = blockTime;
		this.standardFee = standardFee;
		this.websiteUrl = websiteUrl;
		this.createdAt = createdAt;
	}

	public Currency(short currencyId, Employee employee, String name,
			String abbreviation, String symbol, Date launchedOn, int blockTime,
			BigDecimal standardFee, String websiteUrl, Date createdAt,
			Date updatedAt, Set chains) {
		this.currencyId = currencyId;
		this.employee = employee;
		this.name = name;
		this.abbreviation = abbreviation;
		this.symbol = symbol;
		this.launchedOn = launchedOn;
		this.blockTime = blockTime;
		this.standardFee = standardFee;
		this.websiteUrl = websiteUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.chains = chains;
	}

	public short getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(short currencyId) {
		this.currencyId = currencyId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Date getLaunchedOn() {
		return this.launchedOn;
	}

	public void setLaunchedOn(Date launchedOn) {
		this.launchedOn = launchedOn;
	}

	public int getBlockTime() {
		return this.blockTime;
	}

	public void setBlockTime(int blockTime) {
		this.blockTime = blockTime;
	}

	public BigDecimal getStandardFee() {
		return this.standardFee;
	}

	public void setStandardFee(BigDecimal standardFee) {
		this.standardFee = standardFee;
	}

	public String getWebsiteUrl() {
		return this.websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getChains() {
		return this.chains;
	}

	public void setChains(Set chains) {
		this.chains = chains;
	}

}
