package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private Person person;
	private Date createdAt;
	private Set wallets = new HashSet(0);
	private Set addressBookEntries = new HashSet(0);

	public Customer() {
	}

	public Customer(Person person, Date createdAt) {
		this.person = person;
		this.createdAt = createdAt;
	}

	public Customer(Person person, Date createdAt, Set wallets,
			Set addressBookEntries) {
		this.person = person;
		this.createdAt = createdAt;
		this.wallets = wallets;
		this.addressBookEntries = addressBookEntries;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set getWallets() {
		return this.wallets;
	}

	public void setWallets(Set wallets) {
		this.wallets = wallets;
	}

	public Set getAddressBookEntries() {
		return this.addressBookEntries;
	}

	public void setAddressBookEntries(Set addressBookEntries) {
		this.addressBookEntries = addressBookEntries;
	}

}
