package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int employeeId;
	private Person person;
	private Date bornOn;
	private String iban;
	private Date employedOn;
	private Date resignedOn;
	private boolean isActive;
	private Date createdAt;
	private Set members = new HashSet(0);
	private Set employeeRoles = new HashSet(0);
	private Set currencies = new HashSet(0);
	private Set chainsForCreatedBy = new HashSet(0);
	private Set chainsForUpdatedBy = new HashSet(0);
	private Set addressTypesForCreatedBy = new HashSet(0);
	private Set addressTypesForUpdatedBy = new HashSet(0);

	public Employee() {
	}

	public Employee(Person person, Date bornOn, String iban, Date employedOn,
			boolean isActive, Date createdAt) {
		this.person = person;
		this.bornOn = bornOn;
		this.iban = iban;
		this.employedOn = employedOn;
		this.isActive = isActive;
		this.createdAt = createdAt;
	}

	public Employee(Person person, Date bornOn, String iban, Date employedOn,
			Date resignedOn, boolean isActive, Date createdAt,
			Set employeeRoles, Set members, Set chainsForCreatedBy,
			Set addressTypesForUpdatedBy, Set chainsForUpdatedBy,
			Set currencies, Set addressTypesForCreatedBy) {
		this.person = person;
		this.bornOn = bornOn;
		this.iban = iban;
		this.employedOn = employedOn;
		this.resignedOn = resignedOn;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.employeeRoles = employeeRoles;
		this.members = members;
		this.chainsForCreatedBy = chainsForCreatedBy;
		this.addressTypesForUpdatedBy = addressTypesForUpdatedBy;
		this.chainsForUpdatedBy = chainsForUpdatedBy;
		this.currencies = currencies;
		this.addressTypesForCreatedBy = addressTypesForCreatedBy;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Date getBornOn() {
		return this.bornOn;
	}

	public void setBornOn(Date bornOn) {
		this.bornOn = bornOn;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public Date getEmployedOn() {
		return this.employedOn;
	}

	public void setEmployedOn(Date employedOn) {
		this.employedOn = employedOn;
	}

	public Date getResignedOn() {
		return this.resignedOn;
	}

	public void setResignedOn(Date resignedOn) {
		this.resignedOn = resignedOn;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Set getEmployeeRoles() {
		return this.employeeRoles;
	}

	public void setEmployeeRoles(Set employeeRoles) {
		this.employeeRoles = employeeRoles;
	}

	public Set getMembers() {
		return this.members;
	}

	public void setMembers(Set members) {
		this.members = members;
	}

	public Set getChainsForCreatedBy() {
		return this.chainsForCreatedBy;
	}

	public void setChainsForCreatedBy(Set chainsForCreatedBy) {
		this.chainsForCreatedBy = chainsForCreatedBy;
	}

	public Set getAddressTypesForUpdatedBy() {
		return this.addressTypesForUpdatedBy;
	}

	public void setAddressTypesForUpdatedBy(Set addressTypesForUpdatedBy) {
		this.addressTypesForUpdatedBy = addressTypesForUpdatedBy;
	}

	public Set getChainsForUpdatedBy() {
		return this.chainsForUpdatedBy;
	}

	public void setChainsForUpdatedBy(Set chainsForUpdatedBy) {
		this.chainsForUpdatedBy = chainsForUpdatedBy;
	}

	public Set getCurrencies() {
		return this.currencies;
	}

	public void setCurrencies(Set currencies) {
		this.currencies = currencies;
	}

	public Set getAddressTypesForCreatedBy() {
		return this.addressTypesForCreatedBy;
	}

	public void setAddressTypesForCreatedBy(Set addressTypesForCreatedBy) {
		this.addressTypesForCreatedBy = addressTypesForCreatedBy;
	}

}
