package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private int memberId;
	private Employee employee;
	private String username;
	private String password;
	private String emailAddress;
	private String phoneNumber;
	private short failedLogins;
	private boolean isActive;
	private Date registeredAt;
	private Date updatedAt;
	private Set visits = new HashSet(0);
	private Person person;

	public Member() {
	}

	public Member(int memberId, String username, String password,
			String emailAddress, String phoneNumber, short failedLogins,
			boolean isActive, Date registeredAt) {
		this.memberId = memberId;
		this.username = username;
		this.password = password;
		this.emailAddress = emailAddress;
		this.phoneNumber = phoneNumber;
		this.failedLogins = failedLogins;
		this.isActive = isActive;
		this.registeredAt = registeredAt;
	}

	public Member(int memberId, Employee employee, String username,
			String password, String emailAddress, String phoneNumber,
			short failedLogins, boolean isActive, Date registeredAt,
			Date updatedAt, Set visits, Person person) {
		this.memberId = memberId;
		this.employee = employee;
		this.username = username;
		this.password = password;
		this.emailAddress = emailAddress;
		this.phoneNumber = phoneNumber;
		this.failedLogins = failedLogins;
		this.isActive = isActive;
		this.registeredAt = registeredAt;
		this.updatedAt = updatedAt;
		this.visits = visits;
		this.person = person;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public short getFailedLogins() {
		return this.failedLogins;
	}

	public void setFailedLogins(short failedLogins) {
		this.failedLogins = failedLogins;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Date getRegisteredAt() {
		return this.registeredAt;
	}

	public void setRegisteredAt(Date registeredAt) {
		this.registeredAt = registeredAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getVisits() {
		return this.visits;
	}

	public void setVisits(Set visits) {
		this.visits = visits;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
