package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PaymentRequest generated by hbm2java
 */
public class PaymentRequest implements java.io.Serializable {

	private long paymentRequestId;
	private Address address;
	private BigDecimal amount;
	private String message;
	private Date requestedAt;

	public PaymentRequest() {
	}

	public PaymentRequest(long paymentRequestId, Address address,
			BigDecimal amount, Date requestedAt) {
		this.paymentRequestId = paymentRequestId;
		this.address = address;
		this.amount = amount;
		this.requestedAt = requestedAt;
	}

	public PaymentRequest(long paymentRequestId, Address address,
			BigDecimal amount, String message, Date requestedAt) {
		this.paymentRequestId = paymentRequestId;
		this.address = address;
		this.amount = amount;
		this.message = message;
		this.requestedAt = requestedAt;
	}

	public long getPaymentRequestId() {
		return this.paymentRequestId;
	}

	public void setPaymentRequestId(long paymentRequestId) {
		this.paymentRequestId = paymentRequestId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getRequestedAt() {
		return this.requestedAt;
	}

	public void setRequestedAt(Date requestedAt) {
		this.requestedAt = requestedAt;
	}

}
