package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private short roleId;
	private String code;
	private String name;
	private Set employeeRoles = new HashSet(0);

	public Role() {
	}

	public Role(short roleId, String code, String name) {
		this.roleId = roleId;
		this.code = code;
		this.name = name;
	}

	public Role(short roleId, String code, String name, Set employeeRoles) {
		this.roleId = roleId;
		this.code = code;
		this.name = name;
		this.employeeRoles = employeeRoles;
	}

	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getEmployeeRoles() {
		return this.employeeRoles;
	}

	public void setEmployeeRoles(Set employeeRoles) {
		this.employeeRoles = employeeRoles;
	}

}
