package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionEndpointType generated by hbm2java
 */
public class TransactionEndpointType implements java.io.Serializable {

	private short transactionEndpointTypeId;
	private String code;
	private String name;
	private Set transactionEndpoints = new HashSet(0);

	public TransactionEndpointType() {
	}

	public TransactionEndpointType(short transactionEndpointTypeId,
			String code, String name) {
		this.transactionEndpointTypeId = transactionEndpointTypeId;
		this.code = code;
		this.name = name;
	}

	public TransactionEndpointType(short transactionEndpointTypeId,
			String code, String name, Set transactionEndpoints) {
		this.transactionEndpointTypeId = transactionEndpointTypeId;
		this.code = code;
		this.name = name;
		this.transactionEndpoints = transactionEndpoints;
	}

	public short getTransactionEndpointTypeId() {
		return this.transactionEndpointTypeId;
	}

	public void setTransactionEndpointTypeId(short transactionEndpointTypeId) {
		this.transactionEndpointTypeId = transactionEndpointTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTransactionEndpoints() {
		return this.transactionEndpoints;
	}

	public void setTransactionEndpoints(Set transactionEndpoints) {
		this.transactionEndpoints = transactionEndpoints;
	}

}
