package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionStatusType generated by hbm2java
 */
public class TransactionStatusType implements java.io.Serializable {

	private short transactionStatusTypeId;
	private String code;
	private String name;
	private Set transactionses = new HashSet(0);

	public TransactionStatusType() {
	}

	public TransactionStatusType(short transactionStatusTypeId, String code,
			String name) {
		this.transactionStatusTypeId = transactionStatusTypeId;
		this.code = code;
		this.name = name;
	}

	public TransactionStatusType(short transactionStatusTypeId, String code,
			String name, Set transactionses) {
		this.transactionStatusTypeId = transactionStatusTypeId;
		this.code = code;
		this.name = name;
		this.transactionses = transactionses;
	}

	public short getTransactionStatusTypeId() {
		return this.transactionStatusTypeId;
	}

	public void setTransactionStatusTypeId(short transactionStatusTypeId) {
		this.transactionStatusTypeId = transactionStatusTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
