package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionEndpoint generated by hbm2java
 */
public class TransactionEndpoint implements java.io.Serializable {

	private long transactionEndpointId;
	private Address address;
	private TransactionEndpointType transactionEndpointType;
	private Transactions transactions;
	private BigDecimal amount;
	private Date loggedAt;

	public TransactionEndpoint() {
	}

	public TransactionEndpoint(long transactionEndpointId, Address address,
			TransactionEndpointType transactionEndpointType,
			Transactions transactions, BigDecimal amount, Date loggedAt) {
		this.transactionEndpointId = transactionEndpointId;
		this.address = address;
		this.transactionEndpointType = transactionEndpointType;
		this.transactions = transactions;
		this.amount = amount;
		this.loggedAt = loggedAt;
	}

	public long getTransactionEndpointId() {
		return this.transactionEndpointId;
	}

	public void setTransactionEndpointId(long transactionEndpointId) {
		this.transactionEndpointId = transactionEndpointId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public TransactionEndpointType getTransactionEndpointType() {
		return this.transactionEndpointType;
	}

	public void setTransactionEndpointType(
			TransactionEndpointType transactionEndpointType) {
		this.transactionEndpointType = transactionEndpointType;
	}

	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Date getLoggedAt() {
		return this.loggedAt;
	}

	public void setLoggedAt(Date loggedAt) {
		this.loggedAt = loggedAt;
	}

}
