package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private long transactionId;
	private TransactionStatusType transactionStatusType;
	private String localUid;
	private String networkUid;
	private Date receivedAt;
	private Date confirmedAt;
	private Date completedAt;
	private Integer blockHeight;
	private int binarySize;
	private BigDecimal fee;
	private BigDecimal unitPrice;
	private String note;
	private Date loggedAt;
	private Date updatedAt;
	private Set transactionEndpoints = new HashSet(0);

	public Transactions() {
	}

	public Transactions(long transactionId,
			TransactionStatusType transactionStatusType, String localUid,
			String networkUid, Date receivedAt, int binarySize, BigDecimal fee,
			BigDecimal unitPrice, Date loggedAt) {
		this.transactionId = transactionId;
		this.transactionStatusType = transactionStatusType;
		this.localUid = localUid;
		this.networkUid = networkUid;
		this.receivedAt = receivedAt;
		this.binarySize = binarySize;
		this.fee = fee;
		this.unitPrice = unitPrice;
		this.loggedAt = loggedAt;
	}

	public Transactions(long transactionId,
			TransactionStatusType transactionStatusType, String localUid,
			String networkUid, Date receivedAt, Date confirmedAt,
			Date completedAt, Integer blockHeight, int binarySize,
			BigDecimal fee, BigDecimal unitPrice, String note, Date loggedAt,
			Date updatedAt, Set transactionEndpoints) {
		this.transactionId = transactionId;
		this.transactionStatusType = transactionStatusType;
		this.localUid = localUid;
		this.networkUid = networkUid;
		this.receivedAt = receivedAt;
		this.confirmedAt = confirmedAt;
		this.completedAt = completedAt;
		this.blockHeight = blockHeight;
		this.binarySize = binarySize;
		this.fee = fee;
		this.unitPrice = unitPrice;
		this.note = note;
		this.loggedAt = loggedAt;
		this.updatedAt = updatedAt;
		this.transactionEndpoints = transactionEndpoints;
	}

	public long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(long transactionId) {
		this.transactionId = transactionId;
	}

	public TransactionStatusType getTransactionStatusType() {
		return this.transactionStatusType;
	}

	public void setTransactionStatusType(
			TransactionStatusType transactionStatusType) {
		this.transactionStatusType = transactionStatusType;
	}

	public String getLocalUid() {
		return this.localUid;
	}

	public void setLocalUid(String localUid) {
		this.localUid = localUid;
	}

	public String getNetworkUid() {
		return this.networkUid;
	}

	public void setNetworkUid(String networkUid) {
		this.networkUid = networkUid;
	}

	public Date getReceivedAt() {
		return this.receivedAt;
	}

	public void setReceivedAt(Date receivedAt) {
		this.receivedAt = receivedAt;
	}

	public Date getConfirmedAt() {
		return this.confirmedAt;
	}

	public void setConfirmedAt(Date confirmedAt) {
		this.confirmedAt = confirmedAt;
	}

	public Date getCompletedAt() {
		return this.completedAt;
	}

	public void setCompletedAt(Date completedAt) {
		this.completedAt = completedAt;
	}

	public Integer getBlockHeight() {
		return this.blockHeight;
	}

	public void setBlockHeight(Integer blockHeight) {
		this.blockHeight = blockHeight;
	}

	public int getBinarySize() {
		return this.binarySize;
	}

	public void setBinarySize(int binarySize) {
		this.binarySize = binarySize;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getLoggedAt() {
		return this.loggedAt;
	}

	public void setLoggedAt(Date loggedAt) {
		this.loggedAt = loggedAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getTransactionEndpoints() {
		return this.transactionEndpoints;
	}

	public void setTransactionEndpoints(Set transactionEndpoints) {
		this.transactionEndpoints = transactionEndpoints;
	}

}
