package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Visit generated by hbm2java
 */
public class Visit implements java.io.Serializable {

	private long visitId;
	private Member member;
	private String ipAddress;
	private Date loginAt;

	public Visit() {
	}

	public Visit(long visitId, Member member, String ipAddress, Date loginAt) {
		this.visitId = visitId;
		this.member = member;
		this.ipAddress = ipAddress;
		this.loginAt = loginAt;
	}

	public long getVisitId() {
		return this.visitId;
	}

	public void setVisitId(long visitId) {
		this.visitId = visitId;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Date getLoginAt() {
		return this.loginAt;
	}

	public void setLoginAt(Date loginAt) {
		this.loginAt = loginAt;
	}

}
