package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * WalletStateType generated by hbm2java
 */
public class WalletStateType implements java.io.Serializable {

	private short walletStateTypeId;
	private String code;
	private String name;
	private Set wallets = new HashSet(0);

	public WalletStateType() {
	}

	public WalletStateType(short walletStateTypeId, String code, String name) {
		this.walletStateTypeId = walletStateTypeId;
		this.code = code;
		this.name = name;
	}

	public WalletStateType(short walletStateTypeId, String code, String name,
			Set wallets) {
		this.walletStateTypeId = walletStateTypeId;
		this.code = code;
		this.name = name;
		this.wallets = wallets;
	}

	public short getWalletStateTypeId() {
		return this.walletStateTypeId;
	}

	public void setWalletStateTypeId(short walletStateTypeId) {
		this.walletStateTypeId = walletStateTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getWallets() {
		return this.wallets;
	}

	public void setWallets(Set wallets) {
		this.wallets = wallets;
	}

}
