package com.neemre.bitplexus.backend.model.zgen;

// Generated Jul 15, 2015 5:58:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Wallet generated by hbm2java
 */
public class Wallet implements java.io.Serializable {

	private int walletId;
	private Customer customer;
	private WalletStateType walletStateType;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set addresses = new HashSet(0);

	public Wallet() {
	}

	public Wallet(int walletId, Customer customer,
			WalletStateType walletStateType, String name, Date createdAt) {
		this.walletId = walletId;
		this.customer = customer;
		this.walletStateType = walletStateType;
		this.name = name;
		this.createdAt = createdAt;
	}

	public Wallet(int walletId, Customer customer,
			WalletStateType walletStateType, String name, Date createdAt,
			Date updatedAt, Set addresses) {
		this.walletId = walletId;
		this.customer = customer;
		this.walletStateType = walletStateType;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.addresses = addresses;
	}

	public int getWalletId() {
		return this.walletId;
	}

	public void setWalletId(int walletId) {
		this.walletId = walletId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public WalletStateType getWalletStateType() {
		return this.walletStateType;
	}

	public void setWalletStateType(WalletStateType walletStateType) {
		this.walletStateType = walletStateType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
